### ISSUE TITLE
Cannot run ">Literate: Process" for this extension

### ISSUE THREAD

**Issue by kwk** [jesterKing/literate#20]
I've opened the `index.literate` in VSCode and tried running `>Literate: Process` and it failed (see below).

I expected to regenerate the code for this extension but apparently I'm doing something wrong?

I'm running this extension version

```
Released on 5.3.2021, 09:17:48
Last updated 15.1.2022, 21:17:35
Identifier jesterking.literate
```

And this is my VSCode:

```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.16-200.fc35.x86_64
```

This is the error I got:

![Bildschirmfoto von 2022-02-04 22-30-02](https://user-images.githubusercontent.com/193408/152605835-5aee5cef-c8fe-476a-b484-e7b4d59e202e.png)

**Comment by jesterKing** [comment]
This used to be a problem, but at least in current main I don't get this problem anymore.

Are you sure you are using the latest version v0.9.0? It should have for instance the `literate fragments` explorer that I don't see in your side bar. And you should have a number of coding tools like going to definitions, seeing references, splitting fragments, creating new fragments for fragment names that aren't found.

**Comment by jesterKing** [comment]
Forgot to add: there should be no need to run `Literate: Process` manually with the latest version of the extension either, as files are parsed and generated on document edit.

**Comment by kwk** [comment]
I've installed the extension with VSCode itself and there seems to be no v0.9.0 available. How am I supposed to install this? Does v0.9.0 require a specific version of VSCode?

![Bildschirmfoto von 2022-02-04 23-23-18](https://user-images.githubusercontent.com/193408/152611539-b7ac4ebb-aba2-4140-99d6-b2c0dba387dc.png)

**Comment by jesterKing** [comment]
https://marketplace.visualstudio.com/items?itemName=jesterking.literate

If you click the v-icon next to Uninstall you should see a menu entry to install another version:

<img width="252" alt="kuva" src="https://user-images.githubusercontent.com/87916/152611915-a10d5cdd-ad03-45e1-a54d-afda9185f605.png">

That should give you a long list of versions to install:

<img width="247" alt="kuva" src="https://user-images.githubusercontent.com/87916/152611947-90ca125c-f8fd-49f4-9c40-734ee5df821c.png">

**Comment by jesterKing** [comment]
Oh, for what it is worth, I am on 1.64.0 of vscode.

**Comment by kwk** [comment]
I've updated vscode and now v0.9.0 is available. Thank you for your patience.
