### ISSUE TITLE
Trouble building the extension

### ISSUE THREAD

**Issue by RossBoylan** [jesterKing/literate#26]
I thought I'd make a small change so that the preview showed the file name for fragments that specify one.  But I haven't been able get a debug session to run, seemingly getting stuck on the build step (the status bar shows Building and a spinning icon that never stops, and it never launches a debug section).

See [extension can't find lots of modules](https://github.com/microsoft/vscode-discussions/discussions/941) for my attempts to build the extension.  Note that @alefragnani, who helped me, reported that he *was* able to debug the extension after following the steps he gave.  But for some reason they don't work for me.

BTW, @alefragnani suggested a `Contributing.md` file with build instructions is good practice.

The feedback on the status bar and some of the output logs suggest that the debug, presumably in its prelaunch build step, is triggering the `CMake` build system or, when I disabled those extension, `julia`.  `defaultBuildTask` seems to be set to `npm: watch`.

Some of the earlier steps I did by hand seemed to work:

```
PS C:\Users\rdboylan\Documents\literate> npm run compile

> literate@0.10.2-rb1 compile
> tsc -p ./

PS C:\Users\rdboylan\Documents\literate> npm run esbuild

> literate@0.10.2-rb1 esbuild
> npm run -S esbuild-base -- --sourcemap
> npm run -S esbuild-base -- --sourcemap


> literate@0.10.2-rb1 esbuild-base
> esbuild ./src/extension.ts --bundle --outfile=out/main.js --external:vscode --format=cjs --platform=nod> esbuild ./src/> esbuild ./src/extension.ts --bundle --outfile=out/main.js --external:vscode --format=cjs --platform=node --sourcemap
> esbuild ./src/extension.ts --bundle --outfile=out/main.js --external:vscode --format=cjs --platform=nod
e --sourcemap


  out\main.js      1.7mb
  out\main.js.map  2.5mb

Done in 102ms
```

But when I debug running the extension:
```
Executing task: npm run watch 

> literate@0.10.2-rb1 watch
> tsc -watch -p ./

#lots of vertical whitespace

[12:25:38 PM] Starting compilation in watch mode...
```
and that's it.

**Comment by jesterKing** [comment]
I have added a CONTRIBUTING.md file, but in short this is what I did:

* install yarn
* install typescript
* run: yarn
* run: yarn compile
* run: yarn esbuild
* in Run and Debug panel ensure Run Extension is selected, then either press F5 or the green run arrow

That should get the extension running in a new VSCode window. Any breakpoints set in the main VSCode window from which you started the debug session should get hit.

Let me know if that works for you.

**Comment by RossBoylan** [comment]
I went through all the steps ([transcript attached](https://github.com/jesterKing/literate/files/13506840/PowerShell_transcript.EB-WS-12.CyV4EUK%2B.20231129124259.txt)), but seemingly ended up in the same place.

Actually, if I select the debug panel and then pick from the debug drop down at its top, nothing at all seems to happen.  If I go to `extension.ts` and hit `F5` I seem to get a repeat of my initial report.

The `launch.json` configuration for "Run Extension" has `"preLaunchTask": "${defaultBuildTask}"` and my default build task from `Tasks: Configure default build Task` is `tsc -watch -p ./`.  If I execute that by hand in a PowerShell terminal within `VSCode`:
```
[3:51:10 PM] Starting compilation in watch mode...

[3:51:12 PM] Found 0 errors. Watching for file changes.
```
but it does not return to the command line.  So if `VSCode` is waiting for the command to terminate, it will never move on, which is what happens.

I do not know if the command is being executed in `PowerShell` by `VSCode` as part of the build process.

Speculation
------------

1. Could it be an MS-Windows thing and `./` needs to be `.\`?
2. Should it be requesting a `-watch`?
3. Maybe one of the other warnings, esp about version incompatibility, is more serious that it sounds? The attached transcript warns that my version of typescript is too recent.
4. One of my other extensions is interfering.  As noted, there are signs that the build process is triggering both `CMake` and `julia` activity.  However, I disabled both and got the same results.

**Comment by jesterKing** [comment]
I see, the problem is the watch.

I have changed the default build task to `compile` instead of `watch`.

173bb4189f12672ed41c3fea4871c771973ec1eb

This works also on my Windows box - I also use PowerShell as my main shell there (7.4.0).

I don't know about interference from CMake extension or julia. For CMake I have twxs.cmake installed, julia I am unfamiliar with. What extension ID is that?

**Comment by jesterKing** [comment]
FWIW I have published v0.11.1 to the market place.

Are you able to work with that and latest main?

**Comment by RossBoylan** [comment]
Using latest from github, when I do `yarn pretest` I get
```
PS C:\Users\rdboylan\Documents\literate> yarn pretest
yarn run v1.22.21
warning ..\..\package.json: No license field
warning ***@***.***: The engine "vscode" appears to be invalid.

…
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.9.5
…

C:\Users\rdboylan\Documents\literate\src\extension.ts
  323:64  warning  Missing semicolon  @typescript-eslint/semi

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.
```
I’m not sure why it says 1 warning; there are 3 mentioned at various points.  The warning about “vscode” and the TypeScript version were there before; the missing semicolon might be new.

After `yarn esbuild`, with `extension.ts` having focus, I am able to launch a debug session that even stops at a breakpoint.

I got to that point with the version as of this AM, but I had to fiddle a bunch of things first.  This time it worked out of the box!
Thank you.

**Comment by RossBoylan** [comment]
Responding to earlier stuff.

The `julia` extension id is julialang.language-julia.

Reading about the initial problems, it seems handling long-running processes, at least on Windows, has been a recurring problem area.  I found a 2022 [report](https://stackoverflow.com/a/74387498/4409451) of it not working, followed by an even more recent one that it was.  Older reports have problems attributed to failure to provide a full set of pattern specifications for the background task.  The [authoritative](https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks) documentation has a pretty elaborate setup for a background task.  I don't know to what extent `"problemMatcher": "$tsc-watch"`  is a substitute.

By the way, should that `$tsc` since it's not watching?
