### ISSUE TITLE
Bad Output Code Path -> infinite wait

### ISSUE THREAD

**Issue by RossBoylan** [jesterKing/literate#35]
An invalid path for an output file produced a continuous stream of errors (once I looked at the right Output selection) and made it impossible to paste text into the file I was editing--there was just a continuously spinning circle.

Only fixing the path and restarting `VSCode` cured the problem.

Desired Behavior
------------------

It would be nice if it failed more gracefully and more noticeably in these situations.

A more graceful failure would give up if the path is no good and allow other operations to proceed.

A more noticeable failure would have some kind of user feedback, like an alert, that the path was invalid.

Why was the path invalid?
---------------------------

I think the failure was partly the result of #34.  The path for the output file was `../bin/js/foo.js`.  Because of #34 an ordinary file named `bin`, as well as one named `bi` was created in the directory.  The subsequent effort to create a directory below `bin` failed, since it wasn't a directory.

The other part of the problem was that I thought the path should be relative to the directory containing the `.literate` file; the `README` is quite clear that relative paths start from the project root.  This matters because there was already a `bin` directory within the project, and so presumably that particular problem would not have occurred.

There are, of course, many other reasons a path could be invalid: reference to an unwriteable location, reference to a non-existent file system, to an NFS share that disappeared, or even a path that is invalid in the narrow sense of violating the requirements of the operating system: wrong characters, wrong length, etc.

**Comment by jesterKing** [comment]
I believe I fixed the error with d648e85662486746b6f8c65cce525ac7fa5bf1d1 

v0.13.0 of the extension with the fix is now published to the marketplace. Could you please test this to confirm?

**Comment by jesterKing** [comment]
Based on my own testing I think this is solved now. Closing.

If you find there are still issues with this area please log a new issue.
